[package]
name = "aks-v2"
version = "0.1.0"
edition = "2021"
authors = ["Vincent Renders <vince@render3d.tech>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.4"
rug = "1.24.1"
